//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpidySense.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUrlField
    {
        public int Id { get; set; }
        public int WebUrlId { get; set; }
        public string Name { get; set; }
        public string Selector { get; set; }
    
        public virtual WebUrl WebUrl { get; set; }
    }
}
